### ISSUE TITLE
eliminare la repo inattivo: ipim-laboratorio-di-applicazioni-mobili

### ISSUE THREAD

**Issue by ngljcb** [csunibo/laboratorio-di-applicazioni-mobili#12]
@ali-benny secondo te, posso eliminare questo repo? noi usiamo la repo di informatica, quindi secondo me è inutile mantenere questo repo

**Comment by foxyseta** [comment]
Sì in effetti ogni volta che abbiamo insegnamenti condivisi con altri CdL usiamo sempre una repo unica per avere più materiali disponibili. (vedi alcuni corsi convidisi di ingegneria).

https://github.com/csunibo/config è già aggiornata? Vale a dire, questa repo è già assente da `teachings.json`? `courses.json` contiene già l'altra anziché questa (mi pare di sì)?

**Comment by ngljcb** [comment]
@foxyseta ho ri-controllato, confermo che sono assente da `teachings.json` e `degrees.json` che avevo già sistemato quando abbiamo deciso di utilizzare le repo di informatica.

secondo te posso procedere all'eliminazione?
vale anche per ipim-strategia-aziendale

**Comment by foxyseta** [comment]
Sì assolutamente puoi eliminarle entrambe. Bravissimo che te nei accorto. Ho spostato queste issue nelle repo che non eliminiamo per preservare la storia di questa conversazione.

**Comment by ngljcb** [comment]
@foxyseta grazie! ora procedo
