### ISSUE TITLE
Supporto agli archivi compressi

### ISSUE THREAD

**Issue by foxyseta** [csunibo/laboratorio-di-applicazioni-mobili#2]
@kocierik se vuoi che i tuoi zip siano visibili sul sito, devi metterli nella _whitelist_ delle estensioni non ignorate:
https://github.com/csunibo/laboratorio-di-applicazioni-mobili/blob/03edd94668af536f5bd70eef6eb2421dceb245a8/.github/workflows/build-and-deploy.yml#L22

dovrebbe diventare
```yaml
REGEX_INCLUDE: "\\.(pdf|link|txt|zip)$"
```

**Comment by kocierik** [comment]
grazie! @foxyseta
